// Code generated by protoc-gen-go. DO NOT EDIT.
// source: TestMessage.proto

//by default proto2 is used
//declares the package this protofile belongs to
// syntax = "proto3";

package PbTest

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestMessage_TType int32

const (
	TestMessage_CREATE TestMessage_TType = 0
	TestMessage_UPDATE TestMessage_TType = 1
	TestMessage_DELETE TestMessage_TType = 2
)

var TestMessage_TType_name = map[int32]string{
	0: "CREATE",
	1: "UPDATE",
	2: "DELETE",
}

var TestMessage_TType_value = map[string]int32{
	"CREATE": 0,
	"UPDATE": 1,
	"DELETE": 2,
}

func (x TestMessage_TType) Enum() *TestMessage_TType {
	p := new(TestMessage_TType)
	*p = x
	return p
}

func (x TestMessage_TType) String() string {
	return proto.EnumName(TestMessage_TType_name, int32(x))
}

func (x *TestMessage_TType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TestMessage_TType_value, data, "TestMessage_TType")
	if err != nil {
		return err
	}
	*x = TestMessage_TType(value)
	return nil
}

func (TestMessage_TType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7386151ff8dd077b, []int{0, 0}
}

//declares the message TestMessage
type TestMessage struct {
	ClientName           *string                `protobuf:"bytes,1,req,name=clientName" json:"clientName,omitempty"`
	ClientId             *int32                 `protobuf:"varint,2,req,name=clientId" json:"clientId,omitempty"`
	Description          *string                `protobuf:"bytes,3,opt,name=description,def=NONE" json:"description,omitempty"`
	MessageItems         []*TestMessage_MsgItem `protobuf:"bytes,4,rep,name=messageItems" json:"messageItems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TestMessage) Reset()         { *m = TestMessage{} }
func (m *TestMessage) String() string { return proto.CompactTextString(m) }
func (*TestMessage) ProtoMessage()    {}
func (*TestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7386151ff8dd077b, []int{0}
}

func (m *TestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMessage.Unmarshal(m, b)
}
func (m *TestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMessage.Marshal(b, m, deterministic)
}
func (m *TestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMessage.Merge(m, src)
}
func (m *TestMessage) XXX_Size() int {
	return xxx_messageInfo_TestMessage.Size(m)
}
func (m *TestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TestMessage proto.InternalMessageInfo

const Default_TestMessage_Description string = "NONE"

func (m *TestMessage) GetClientName() string {
	if m != nil && m.ClientName != nil {
		return *m.ClientName
	}
	return ""
}

func (m *TestMessage) GetClientId() int32 {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return 0
}

func (m *TestMessage) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return Default_TestMessage_Description
}

func (m *TestMessage) GetMessageItems() []*TestMessage_MsgItem {
	if m != nil {
		return m.MessageItems
	}
	return nil
}

type TestMessage_MsgItem struct {
	Id                   *int32             `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	ItemName             *string            `protobuf:"bytes,2,opt,name=itemName" json:"itemName,omitempty"`
	ItemValue            *int32             `protobuf:"varint,3,opt,name=itemValue" json:"itemValue,omitempty"`
	TransactionType      *TestMessage_TType `protobuf:"varint,4,opt,name=transaction_type,json=transactionType,enum=PbTest.TestMessage_TType" json:"transaction_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TestMessage_MsgItem) Reset()         { *m = TestMessage_MsgItem{} }
func (m *TestMessage_MsgItem) String() string { return proto.CompactTextString(m) }
func (*TestMessage_MsgItem) ProtoMessage()    {}
func (*TestMessage_MsgItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_7386151ff8dd077b, []int{0, 0}
}

func (m *TestMessage_MsgItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMessage_MsgItem.Unmarshal(m, b)
}
func (m *TestMessage_MsgItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMessage_MsgItem.Marshal(b, m, deterministic)
}
func (m *TestMessage_MsgItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMessage_MsgItem.Merge(m, src)
}
func (m *TestMessage_MsgItem) XXX_Size() int {
	return xxx_messageInfo_TestMessage_MsgItem.Size(m)
}
func (m *TestMessage_MsgItem) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMessage_MsgItem.DiscardUnknown(m)
}

var xxx_messageInfo_TestMessage_MsgItem proto.InternalMessageInfo

func (m *TestMessage_MsgItem) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *TestMessage_MsgItem) GetItemName() string {
	if m != nil && m.ItemName != nil {
		return *m.ItemName
	}
	return ""
}

func (m *TestMessage_MsgItem) GetItemValue() int32 {
	if m != nil && m.ItemValue != nil {
		return *m.ItemValue
	}
	return 0
}

func (m *TestMessage_MsgItem) GetTransactionType() TestMessage_TType {
	if m != nil && m.TransactionType != nil {
		return *m.TransactionType
	}
	return TestMessage_CREATE
}

func init() {
	proto.RegisterEnum("PbTest.TestMessage_TType", TestMessage_TType_name, TestMessage_TType_value)
	proto.RegisterType((*TestMessage)(nil), "PbTest.TestMessage")
	proto.RegisterType((*TestMessage_MsgItem)(nil), "PbTest.TestMessage.MsgItem")
}

func init() { proto.RegisterFile("TestMessage.proto", fileDescriptor_7386151ff8dd077b) }

var fileDescriptor_7386151ff8dd077b = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8e, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0xcd, 0x34, 0xa9, 0xe6, 0x46, 0x6a, 0x9c, 0x55, 0xac, 0x22, 0xa1, 0x0b, 0x09, 0x08,
	0x59, 0x74, 0xe9, 0x46, 0xc4, 0xcc, 0xa2, 0x60, 0x63, 0x19, 0xa2, 0x5b, 0x89, 0xc9, 0xa5, 0x0c,
	0x34, 0x3f, 0x64, 0xc6, 0x45, 0x1f, 0xc5, 0x67, 0x75, 0x23, 0x37, 0x91, 0x1a, 0xc1, 0xdd, 0x39,
	0xe7, 0x9b, 0xcb, 0x7c, 0x70, 0x9e, 0xa1, 0x36, 0x6b, 0xd4, 0x3a, 0xdf, 0x62, 0xdc, 0x76, 0x8d,
	0x69, 0xf8, 0x74, 0xf3, 0x4e, 0xe3, 0xe2, 0x8b, 0x81, 0x37, 0xa2, 0xfc, 0x1a, 0xa0, 0xd8, 0x29,
	0xac, 0x4d, 0x9a, 0x57, 0x18, 0x58, 0x21, 0x8b, 0x5c, 0x39, 0x5a, 0xf8, 0x1c, 0x4e, 0x86, 0xb6,
	0x2a, 0x03, 0x16, 0xb2, 0xc8, 0x91, 0x87, 0xce, 0x6f, 0xc0, 0x2b, 0x51, 0x17, 0x9d, 0x6a, 0x8d,
	0x6a, 0xea, 0x60, 0x12, 0x5a, 0x91, 0x7b, 0x67, 0xa7, 0xcf, 0xa9, 0x90, 0x63, 0xc0, 0xef, 0xe1,
	0xb4, 0x1a, 0xbe, 0x5b, 0x19, 0xac, 0x74, 0x60, 0x87, 0x93, 0xc8, 0x5b, 0x5e, 0xc6, 0x83, 0x52,
	0x3c, 0x96, 0x5d, 0xeb, 0x2d, 0xbd, 0x91, 0x7f, 0x0e, 0xe6, 0x9f, 0x16, 0x1c, 0xff, 0x10, 0x3e,
	0x03, 0xa6, 0xca, 0x5e, 0xd4, 0x91, 0x4c, 0x95, 0x24, 0xa8, 0x0c, 0x56, 0xbd, 0x3e, 0x23, 0x03,
	0x79, 0xe8, 0xfc, 0x0a, 0x5c, 0xca, 0xaf, 0xf9, 0xee, 0x03, 0x7b, 0x3d, 0x47, 0xfe, 0x0e, 0x3c,
	0x01, 0xdf, 0x74, 0x79, 0xad, 0xf3, 0x82, 0x2c, 0xdf, 0xcc, 0xbe, 0xc5, 0xc0, 0x0e, 0xad, 0x68,
	0xb6, 0xbc, 0xf8, 0x4f, 0x2d, 0xcb, 0xf6, 0x2d, 0xca, 0xb3, 0xd1, 0x09, 0x0d, 0x8b, 0x5b, 0x70,
	0x7a, 0xc2, 0x01, 0xa6, 0x8f, 0x52, 0x3c, 0x64, 0xc2, 0x3f, 0xa2, 0xfc, 0xb2, 0x49, 0x28, 0x5b,
	0x94, 0x13, 0xf1, 0x24, 0x32, 0xe1, 0xb3, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xea, 0x3d,
	0x30, 0x99, 0x01, 0x00, 0x00,
}
